[package]
name = "odisk"
version = "0.1.1"
authors = ["SpizzyCoder <spizzycoder@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = "0.2"