[package]
name = "odisk"
version = "0.2.0"
authors = ["SpizzyCoder <spizzycoder@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = "0.2"
clap = { version = "3.1.18", features = ["derive"] }